### ISSUE TITLE
Some upgrades / threading

### ISSUE THREAD

**Issue by moebiussurfing** [tettou771/ofxChatGPT#2]
Hey @tettou771 ,

I have seen another repo with two headers that could be maybe useful, almost for inspiration:

https://github.com/Codeant-GitHub/ChatGPT-cpp-main/blob/main/chatgpt-cpp/openai_api_client.h

https://github.com/Codeant-GitHub/ChatGPT-cpp-main/blob/main/chatgpt-cpp/playground.h

I tried to compile that `ChatGPT-cpp-main` repo but I fall stuck on `WinRT` problems.

Btw, I made some experiments with this/your add-on.
I am planing to add it some threading (using `ofThreadChannel`) feature to not lock the drawing.
I'll post you here some links if I have some success on this.

Regards

**Comment by tettou771** [comment]
Hi @moebiussurfing 

I also tried to think of an implementation method to make it work with threads, but I couldn't come up with a simple and elegant solution. Instead, I've created a class called ChatThread that inherits from ofThread in another project and use it there. 
I've implemented a mechanism where, after sending a request using methods like chatAsync(), you can check whether a response has arrived using hasMessage() and then receive that message with getMessage(). I found it cumbersome to use mutex in various places when using ofEvent to send messages, so I implemented it with the intention of calling getMessage() within the update() function.

Here is the link to that:

[ChatThread.h](https://github.com/tettou771/MidiChat/blob/main/src/MidiChat/ChatThread.h)
[ChatThread.cpp](https://github.com/tettou771/MidiChat/blob/main/src/MidiChat/ChatThread.cpp)

I took a brief look at ChatGPT-cpp-main. I haven't gone through it thoroughly since it's quite long. It seems to be a work in progress (history is not yet usable), but it appears to be a smart implementation as it properly uses std::thread.



By the way, I've been having all of my recent messages translated by ChatGPT and have been reading and writing in that way. Has my English become more natural than before? I'm not good at English, so I might not notice if there are any strange parts, but in that case, please file a complaint with OpenAI, haha!

**Comment by moebiussurfing** [comment]
Thanks @tettou771

**Comment by moebiussurfing** [comment]
I did a threaded example with 3 different prompts for asking about 9 hard coded music bands:

https://github.com/moebiussurfing/ofxChatGPT/tree/developThread/example-threaded

I used your threaded ChatThread class. It works fine. Thanks.

You can copy it to include the example if you want or I can prepare tomorrow a PR if you prefer. 

PS
I also tryed to build your MidiChat project on Windows, but I get some utf errors.
Do you have some screens of what it does? I am just curious...

**Comment by tettou771** [comment]
I apologize for the delayed response. I think the example-threaded is a great sample!
I would appreciate it if you could submit a PR.
In the future, we might integrate the thread feature into ofxChatGPT, but it's possible that it might require a different implementation. We will try to maintain compatibility as much as possible.

By the way, I am currently working on an add-on for the voice recognition AI called Whisper (utilizing its API).
https://github.com/tettou771/ofxWhisper/blob/main/src/ofxWhisper.cpp
I am creating this for use in MidiChat, with the intention of having ChatGPT create music by talking to it in words. And then, I plan to have real-time sessions.

The reason the MidiChat build may not have worked well might be because I was using ofxGoogleIME until recently. This was a necessary feature for inputting Japanese with a keyboard, but I'm not using it anymore (instead, I'm using ofxWhisper), so you might be able to build it now.
Here's a link to a slightly older version of the video:
https://twitter.com/tettou771/status/1644451557105336320
